version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: nexorb_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST:${DB_HOST}
      - DB_PORT:${DB_PORT}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_NAME:${DB_NAME}
    depends_on:
      - database
    volumes:
      - .:/app
    networks:
      - nexorb_network 

  database:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexorb_network
networks:
  nexorb_network:

volumes:
  postgres_data:
