package main

import (
	"fmt"
	"github.com/Abiji-2020/NexOrb/config"
	_ "github.com/Abiji-2020/NexOrb/docs" // docs is generated by Swag CLI
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
)

// @title NexOrb API
// @version 1.0
// @description This is the API documentation for NexOrb.
// @host localhost:8080
// @BasePath /v1/api
func main() {
	if err := StartServer(); err != nil {
		fmt.Println("Failed to start server:", err)
	}
}

func StartServer() error {
	app := config.NewConfig()
	if app == nil {
		return fmt.Errorf("error initializing the app")
	}
	app.InitializeRoutes()
	app.Logger.LogInfo("Routes initialized")

	app.Logger.LogInfo("Migrating the database")
	err := app.MigrateDatabase()
	if err != nil {
		app.Logger.LogError(fmt.Sprintf("Error migrating the database: %v", err))
		return err
	}

	// Set up Swagger route
	app.Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the Gin server
	go func() {
		err = app.Router.Run(":" + app.ServerPort)
		if err != nil {
			app.Logger.LogFatal("Failed to start server: " + err.Error())
		}
	}()

	app.Logger.LogInfo("Server started on port " + app.ServerPort)
	return nil
}